import express from "express";
import cors from "cors";
import rateLimit from "express-rate-limit";
import path from "path";
import words from "./models/words";
import wordOfTheDay from "./models/wordOfTheDay";
import { getImage, uploadImageToS3 } from "./services/generateImageWithComfyUI";
import { waitForImageFilename } from "./services/imagePolling";
import authRoutes from "./routes/auth";
import allWordsRoutes from "./routes/allWords";
import uploadExcelRouter from "./routes/uploadExcel";
import subjectRouter from "./routes/subject";
import gradeRouter from "./routes/grade";
import examRouter from "./routes/exam";
import { swaggerSpec } from "./config/swagger";
import { logger } from "./utils/logger";
import { escapeRegex } from "./utils/text";

const limiter = rateLimit({
  windowMs: 15 * 60 * 1000,
  max: 100,
});

const app = express();
const configuredOrigins = (process.env.CORS_ORIGINS || "")
  .split(",")
  .map((origin) => origin.trim())
  .filter(Boolean);

const allowedOrigins = new Set([
  "https://grab-vocab.vercel.app",
  "http://localhost:5173",
  "http://localhost:8081",
  "http://localhost:8082",
  "http://localhost:19006",
  "http://127.0.0.1:5173",
  "http://127.0.0.1:8081",
  "http://127.0.0.1:8082",
  "http://127.0.0.1:19006",
  ...configuredOrigins,
]);

const isAllowedOrigin = (origin: string) => {
  if (allowedOrigins.has(origin)) {
    return true;
  }

  try {
    const url = new URL(origin);
    const isLocalhost =
      url.hostname === "localhost" || url.hostname === "127.0.0.1";
    const isExpoPort = ["5173", "8081", "8082", "19006"].includes(url.port);

    return isLocalhost && isExpoPort;
  } catch {
    return false;
  }
};

const corsOptions: cors.CorsOptions = {
  origin: function (
    origin: string | undefined,
    callback: (err: Error | null, allow?: boolean) => void
  ) {
    if (!origin || isAllowedOrigin(origin)) {
      callback(null, true);
    } else {
      callback(new Error("Not allowed by CORS"));
    }
  },
  credentials: true,
};

app.use(cors(corsOptions)); // ✅ Enable CORS
app.use(express.json());
app.set("trust proxy", 1);
app.use(limiter);

app.get(/^\/docs\/?$/, (_req, res) => {
  res.sendFile(path.join(process.cwd(), "public", "swagger.html"));
});

app.get("/openapi.json", (req, res) => {
  res.json(swaggerSpec);
});

/**
 * @swagger
 * /:
 *   get:
 *     tags:
 *       - Health
 *     summary: Welcome endpoint
 *     description: Returns a welcome message
 *     responses:
 *       200:
 *         description: Welcome message
 */
app.get("/", (req, res) => {
  res.send("Welcome to Dictionary!");
});

/**
 * @swagger
 * /hello:
 *   get:
 *     tags:
 *       - Health
 *     summary: Simple hello endpoint
 *     responses:
 *       200:
 *         description: OK
 */
app.get("/hello", (req, res) => {
  res.send("Hello response!");
});

/**
 * @swagger
 * /define/{word}:
 *   get:
 *     tags:
 *       - Dictionary
 *     summary: Get details for a word
 *     parameters:
 *       - name: word
 *         in: path
 *         required: true
 *         schema:
 *           type: string
 *     responses:
 *       200:
 *         description: Word found
 *       404:
 *         description: Word not found
 */
app.get("/define/:word", async (req, res) => {
  try {
    const term = req.params.word.toLowerCase();
    const existing = await words.findOne({ word: term });
    if (existing) {
      res.json({ term, result: existing, promptId: existing.promptId || null });
      return;
    }
    res.status(404).json({ error: `Word '${term}' not found in database.` });
  } catch (err) {
    logger.error("Error fetching word details", err);
    res.status(500).json({ error: "Something went wrong" });
  }
});

/**
 * @swagger
 * /getImageURL/{promptId}/{word}:
 *   get:
 *     tags:
 *       - Dictionary
 *     summary: Get image URL for generated image
 *     description: Retrieve the AWS S3 URL for an image generated by ComfyUI
 *     parameters:
 *       - name: promptId
 *         in: path
 *         required: true
 *         schema:
 *           type: string
 *         description: ComfyUI prompt ID
 *       - name: word
 *         in: path
 *         required: true
 *         schema:
 *           type: string
 *         description: The word for which image was generated
 *     responses:
 *       200:
 *         description: Image URL retrieved and stored
 *       202:
 *         description: Image still being generated
 *       500:
 *         description: Failed to retrieve image
 */
app.get("/getImageURL/:promptId/:word", async (req, res) => {
  try {
    const { promptId, word } = req.params;

    const filename = await waitForImageFilename(promptId);
    if (!filename) {
      res.status(202).json({ message: "Image not ready", status: "pending" });
      return;
    }

    const imageURL = await getImage(filename);

    if (!imageURL) {
      res.status(500).json({ error: "Failed to retrieve image URL" });
      return;
    }
    const imageAWSURL = await uploadImageToS3(imageURL, filename);
    const updated = await words.findOneAndUpdate(
      { word: new RegExp(`^${escapeRegex(word)}$`, "i") },
      { $set: { imageURL: imageAWSURL } },
      { new: true }
    );

    res.json({ word, imageURL, status: "success", updated });
    return;
  } catch (err) {
    logger.error("Error getting image URL", err);
    res.status(500).json({ error: "Failed to fetch image" });
  }
});

/**
 * @swagger
 * /wordoftheday:
 *   get:
 *     tags:
 *       - Dictionary
 *     summary: Get word of the day
 *     responses:
 *       200:
 *         description: Word of the day
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 word:
 *                   type: string
 *                 meaning:
 *                   type: string
 *                 date:
 *                   type: string
 */
app.get("/wordoftheday", async (req, res) => {
  try {
    const today = new Date().toISOString().split("T")[0];

    const existing = await wordOfTheDay.findOne({ date: today });
    if (existing) {
      res.json({ word: existing.word, meaning: existing.meaning, date: today });
      return;
    }

    const [wordData] = await words.aggregate([{ $sample: { size: 1 } }]);
    if (!wordData?.word || !wordData?.meaning) {
      res.status(404).json({ error: "No words available in database" });
      return;
    }

    const saved = await wordOfTheDay.create({
      word: wordData.word,
      meaning: wordData.meaning,
      date: today,
    });

    res.json({ word: saved.word, meaning: saved.meaning, date: today });
    return;
  } catch (error) {
    logger.error("Error fetching word of the day", error);
    res.status(500).json({ error: "Could not fetch word of the day" });
  }
});

app.use("/subject", subjectRouter);
app.use("/grade", gradeRouter);
app.use("/api", uploadExcelRouter);
app.use("/auth", authRoutes);
app.use("/exam", examRouter);
app.use("/words", allWordsRoutes);
app.use("/allWords", allWordsRoutes);

export default app;
